In [5]:
import numpy as np
from numpy.random import choice

In [52]:
docs = [[0.98, 0.01, 0.01],
        [0.01, 0.98, 0.01],
        [0.01, 0.01, 0.98]]

topics = [[ 0.4,      0.4,   0.01,        0.01,    0.01,       0.01,  0.1,     0.04,   0.01,        0.01],
          [0.01,     0.01,    0.4,         0.4,    0.01,       0.01,  0.1,     0.04,   0.01,        0.01],
          [0.02,     0.02,   0.01,        0.01,     0.4,        0.4, 0.02,      0.1,   0.01,        0.01]]

words =  ['cat', 'kitten',  'dog',     'puppy',  'deep', 'learning','fur',  'image',  'GPU', 'asparagus']

In [73]:
def make_doc(topic_probs, n_words):
    sentence = ''
    for _ in range(n_words):
        topic_index = choice(len(topic_probs) ,p=topic_probs)
        topic = topics[topic_index]
        word = choice(words, p = topic)
        
        sentence += word + ' '
    return sentence


def make_doc2(n_words):
    sentence = ''
    topic_probs = np.random.dirichlet([1,1,1])
    print(topic_probs)
    for _ in range(n_words):
        topic_index = choice(len(topic_probs) ,p=topic_probs)
        topic = topics[topic_index]
        word = choice(words, p = topic)
        
        sentence += word + ' '
    return sentence

In [57]:
for doc in docs:
    print(make_doc(topic_probs=doc, n_words=10))

kitten kitten cat kitten cat fur fur cat fur cat 
puppy dog puppy dog dog dog puppy dog puppy dog 
learning deep deep learning deep learning learning deep deep deep 


In [76]:
for doc in docs:
    print(make_doc2(n_words=10))

[0.93084404 0.05846002 0.01069594]
fur fur cat kitten kitten cat fur kitten dog asparagus 
[0.65109158 0.23891534 0.10999307]
kitten fur puppy fur fur puppy cat puppy asparagus kitten 
[0.3669245  0.40919082 0.22388468]
fur kitten cat fur kitten cat GPU cat learning learning 
